---
title: "R language analysis"
author: "gaoyuhao"
date: 2026-09-28
---

# Introduction
Data source: [Author/Organization], [Year], [Dataset Title]. Available via [Name of Repository/Platform] at [Link or DOI].
We explore the frequency of (non)official languages used in different situations in Canada 


```{r}
#| label: fig-penguin-mass
#| fig-cap: "Body mass of penguins by species."
#| warning: false
#| message: false
library(tidyverse)
```


```{r}
#| label: fig-penguin-mass1
#| fig-cap: "Body mass of penguins by species."
#| warning: false
#| message: false

library(readxl)
library(tidyverse)


# the data shown below comes from the link https://github.com/ttimbers/canlang/raw/master/inst/extdata/victoria_lang.tsv named victoria. It is about the language used at specific situations and their frequency compared in a single table.

victoria <- read_delim("https://raw.githubusercontent.com/ttimbers/canlang/master/inst/extdata/victoria_lang.tsv", delim = "\t")
head(victoria, 20)
```


```{r}
#| label: fig-penguin-mass2
#| fig-cap: "Body mass of penguins by species."
#| warning: false
#| message: false

modified <- victoria |> group_by(language) |> summarize('mean value langage users at home' = mean(most_at_home))

modified

```


```{r}
#| label: fig-penguin-mass3
#| fig-cap: "Body mass of penguins by species."
#| warning: false
#| message: false

modified1 <- victoria |> group_by(language) |> summarize('mean value langage users at work' = mean(most_at_work))

modified1

```

```{r}
#| label: fig-penguin-mass4
#| fig-cap: "Body mass of penguins by species."
#| warning: false
#| message: false

modified2 <- victoria |> group_by(language) |> summarize('mean value langage users at home' = mean(lang_known))

modified2

```
```{r}
library(tidyverse)

victoria |>
  
  slice_max(lang_known, n = 10) |>
  
  pivot_longer(
    cols = c(most_at_home, most_at_work, lang_known),
    names_to = "usage_type",
    values_to = "count"
  ) |>
  ggplot(aes(x = language, y = count, fill = category)) +
  geom_col(position = "dodge") +
  theme_minimal() +
  labs(
    title = "Language usage in Victoria",
    x = "Language",
    y = "Number of people",
    fill = "Usage type"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```
In the three chunks of codes above I calculate the mean value of people number who speaks different catories of laguage and who speaks them mostly at home and work, as well as the reputation of the languages to some extent. In conclusion, when people are at home, they speak Arabiuc most often. While they work outside, both Arabic and American Sign Language are spoken mostly. As for the languages people known most, comparing rows of the third table, we know Arabic, Afrikaans, and American Sign Language hold the most part life of people. Generally speaking, Arabic is the one people like most since they talk to their, for example, wife, husband, parents, using it, while more official language to some extent is American Sign Language since it has been used to work. It is not strange that American Sign Language is the second mostly used one since it has connected some big company in America, for example. Of course, people can also speak Albanian sometimes.

```


